colorScheme = "jeroscope" 
defaultAppearance = "dark"

[params.homepage]
  layout = "custom"

[params.list]
  cardView = true
  showSummary = true
  showAuthor = true
  showDate = true
  showTaxonomies = true
  showReadingTime = false
  showWordCount = false

[params.article]
  showAuthorsBadges = true
  showTaxonomies = true
  showReadingTime = false
  showWordCount = false