baseURL = 'https://jeroscope.com/'
languageCode = 'en-us'
title = 'JeroScope'
theme = "blowfish"

[languages.en.menu]

  [[languages.en.menu.main]]
  name   = "Home"
  url    = "/"
  weight = 10

  [[languages.en.menu.main]]
  name   = "Projects"
  url    = "/projects/"
  weight = 20

  [[languages.en.menu.main]]
  name   = "Blogs"
  url    = "/blogs/"
  weight = 30

  [[languages.en.menu.main]]
  name   = "Advisories"
  url    = "/advisories/"
  weight = 40

  [[languages.en.menu.main]]
  name   = "Contact"
  url    = "/contact/"
  weight = 50

[languages.ko.menu]

  [[languages.ko.menu.main]]
  name   = "Home"
  url    = "/ko/"
  weight = 10

  [[languages.ko.menu.main]]
  name   = "Projects"
  url    = "/ko/projects/"
  weight = 20

  [[languages.ko.menu.main]]
  name   = "Blogs"
  url    = "/ko/blogs/"
  weight = 30

  [[languages.ko.menu.main]]
  name   = "Advisories"
  url    = "/ko/advisories/"
  weight = 40

  [[languages.ko.menu.main]]
  name   = "Contact"
  url    = "/ko/contact/"
  weight = 50

  [params.homepage]
  layout = "custom"

  [params.list]
  cardView = true              
  showSummary = true

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    tabWidth = 4